### ISSUE TITLE
Toolbar: Too generic CSS class "ab-icon" for trash icon

### ISSUE THREAD

**Issue by tyrann0us** [pluginkollektiv/cachify#37] opened 2016-08-01 12:36 UTC
The CSS class for specifiying the trash dashicon is `ab-icon`. This seems to be too generic since other plugins/themes might use the same class and thus get a wrong icon. Better use `dashicons-trash`.

Example plugin: [The Events Calendar](https://wordpress.org/plugins/the-events-calendar/).

**Comment by swissspidy** [comment] 2016-08-01 13:16
Thanks for your report!

I will close this as a duplicate of #25 which already fixed this bug.

We're planning to release a maintenance release soon which will include this fix.

**Closed by swissspidy** 2016-08-01 13:16 UTC

**Comment by tyrann0us** [comment] 2016-08-01 13:35
Sorry, I missed this one.

**Comment by swissspidy** [comment] 2016-08-01 13:44
No problem, I'm glad you took the time to report it anyway :)
