### ISSUE TITLE
Invalid robots.txt entry by disallowing /wp-content/cache/cachify

### ISSUE THREAD

**Issue by hostz-frank** [pluginkollektiv/cachify#299] opened 2024-06-05 21:47 UTC
That's a valid output section for the robots_txt function inside inc/class-cachify.php:
```
/* Output */
$data .= sprintf(
    '%2$sUser-agent: *%2$sDisallow: %1$s/wp-content/cache/cachify/%2$s',
    ( empty( $url_parts['path'] ) ? '' : $url_parts['path'] ),
    PHP_EOL
);
```
You need to output the User-agent line before disallowing something since you cannot rely on it as already existing. In my case I've seen the plugin's output as first entry of robots.txt which produced an invalid robots.txt file.

**Comment by stklcode** [comment] 2024-06-06 05:07
duplicate of #282, should be already fixed in #283

**Comment by hostz-frank** [comment] 2024-06-12 17:37
It's not fixed on wordpress.org. What lives there is v2.3.2 of Cachify - in  that version it is not fixed. Latest update there is 2,5 years old. Doesn't even look like maintained at all.

**Comment by stklcode** [comment] 2024-06-12 18:10
Yes, that's true. Nothing to sugarcoat about that.

The issue is fixed in current development state though, so no point keeping this open here. We should push for a release of v2.4.0 (#293) to make this fix available.

**Closed as completed by stklcode** 2024-06-12 18:10 UTC
Labels: bug, duplicate
